### ISSUE TITLE
Slick Vertical text cut off issue

### ISSUE THREAD

**Issue by yushanwebdev** [yushanwebdev/problems#2]
Can somebody help me to find a solution to for this text cut off issue
URL :- https://yushanwebdev.github.io/problems/slick-vertical-text-cut-off/

**Comment by old-wrmn** [comment]
Hi yushanwebdev

The problem is on slick-vertical width. Some line are too long so they don't fit in 250 px. 
You can make slick-vertical width larger or make your font size smaller so they fit in one line. if they can't be edited you can break the line after some character.

**Comment by yushanwebdev** [comment]
Hi @warmoa,

What do you mean by this ?

> if they can't be edited you can break the line after some character.

**Comment by old-wrmn** [comment]
i mean if for some reason the width must be 250px and font size is not allowed to be changed you can add line break after some character. 

check [this](https://stackoverflow.com/questions/17895039/how-to-insert-line-break-after-every-80-characters)

**Comment by yushanwebdev** [comment]
@warmoa,

I fixed the issue by adding a calculated height to the parent. Thanks for your help btw.
